// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-gateway-example.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloWorldReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldReq) Reset()         { *m = HelloWorldReq{} }
func (m *HelloWorldReq) String() string { return proto.CompactTextString(m) }
func (*HelloWorldReq) ProtoMessage()    {}
func (*HelloWorldReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f0f8b2cdba5fbb9, []int{0}
}

func (m *HelloWorldReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldReq.Unmarshal(m, b)
}
func (m *HelloWorldReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldReq.Marshal(b, m, deterministic)
}
func (m *HelloWorldReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldReq.Merge(m, src)
}
func (m *HelloWorldReq) XXX_Size() int {
	return xxx_messageInfo_HelloWorldReq.Size(m)
}
func (m *HelloWorldReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldReq proto.InternalMessageInfo

func (m *HelloWorldReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloWorldResp struct {
	Echo                 string   `protobuf:"bytes,2,opt,name=echo,proto3" json:"echo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldResp) Reset()         { *m = HelloWorldResp{} }
func (m *HelloWorldResp) String() string { return proto.CompactTextString(m) }
func (*HelloWorldResp) ProtoMessage()    {}
func (*HelloWorldResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f0f8b2cdba5fbb9, []int{1}
}

func (m *HelloWorldResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldResp.Unmarshal(m, b)
}
func (m *HelloWorldResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldResp.Marshal(b, m, deterministic)
}
func (m *HelloWorldResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldResp.Merge(m, src)
}
func (m *HelloWorldResp) XXX_Size() int {
	return xxx_messageInfo_HelloWorldResp.Size(m)
}
func (m *HelloWorldResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldResp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldResp proto.InternalMessageInfo

func (m *HelloWorldResp) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloWorldReq)(nil), "owenliu1122.grpc_gateway_example.HelloWorldReq")
	proto.RegisterType((*HelloWorldResp)(nil), "owenliu1122.grpc_gateway_example.HelloWorldResp")
}

func init() { proto.RegisterFile("grpc-gateway-example.proto", fileDescriptor_0f0f8b2cdba5fbb9) }

var fileDescriptor_0f0f8b2cdba5fbb9 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x4d, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0xd4, 0x4d, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xc8, 0x2f, 0x4f, 0xcd, 0xcb, 0xc9, 0x2c, 0x35,
	0x34, 0x34, 0x32, 0xd2, 0x03, 0xa9, 0x8b, 0x87, 0xaa, 0x8b, 0x87, 0xaa, 0x93, 0x32, 0x4b, 0xcf,
	0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x2d, 0xcf, 0x2c, 0xc9, 0xce, 0x2f,
	0xd7, 0x4f, 0xcf, 0xd7, 0x05, 0x6b, 0xd7, 0x2d, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0xc9, 0x2f,
	0x2a, 0xd6, 0x87, 0x33, 0x21, 0x26, 0x4b, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27,
	0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x64,
	0x95, 0x6c, 0xb9, 0x78, 0x3d, 0x52, 0x73, 0x72, 0xf2, 0xc3, 0xf3, 0x8b, 0x72, 0x52, 0x82, 0x52,
	0x0b, 0x85, 0x74, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x9d,
	0x24, 0x1e, 0xdd, 0x97, 0x17, 0xd1, 0x12, 0x00, 0x89, 0x28, 0x64, 0x16, 0x2b, 0x14, 0xa5, 0x16,
	0x96, 0x66, 0x16, 0xa5, 0xa6, 0x44, 0x30, 0x06, 0x81, 0x55, 0x29, 0xa9, 0x70, 0xf1, 0x21, 0x6b,
	0x2f, 0x2e, 0x10, 0x12, 0xe2, 0x62, 0x49, 0x4d, 0xce, 0xc8, 0x97, 0x60, 0x02, 0xe9, 0x0f, 0x02,
	0xb3, 0x8d, 0x66, 0x33, 0x72, 0x71, 0x21, 0x94, 0x09, 0xf5, 0xa0, 0x72, 0xf5, 0xf5, 0x08, 0xf9,
	0x5d, 0x0f, 0xc5, 0x89, 0x52, 0x06, 0xa4, 0x69, 0x28, 0x2e, 0x50, 0x92, 0x6e, 0xba, 0xfc, 0x64,
	0x32, 0x93, 0xa8, 0x92, 0x00, 0x38, 0x14, 0x32, 0x40, 0x92, 0xba, 0xe5, 0x20, 0x59, 0x2b, 0x46,
	0x2d, 0x27, 0x96, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0x70, 0x78, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x29, 0xb8, 0x39, 0x4e, 0xa5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloWorldClient is the client API for HelloWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldClient interface {
	HelloWorld(ctx context.Context, in *HelloWorldReq, opts ...grpc.CallOption) (*HelloWorldResp, error)
}

type helloWorldClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldClient(cc *grpc.ClientConn) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) HelloWorld(ctx context.Context, in *HelloWorldReq, opts ...grpc.CallOption) (*HelloWorldResp, error) {
	out := new(HelloWorldResp)
	err := c.cc.Invoke(ctx, "/owenliu1122.grpc_gateway_example.HelloWorld/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldServer is the server API for HelloWorld service.
type HelloWorldServer interface {
	HelloWorld(context.Context, *HelloWorldReq) (*HelloWorldResp, error)
}

// UnimplementedHelloWorldServer can be embedded to have forward compatible implementations.
type UnimplementedHelloWorldServer struct {
}

func (*UnimplementedHelloWorldServer) HelloWorld(ctx context.Context, req *HelloWorldReq) (*HelloWorldResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/owenliu1122.grpc_gateway_example.HelloWorld/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).HelloWorld(ctx, req.(*HelloWorldReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "owenliu1122.grpc_gateway_example.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _HelloWorld_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-gateway-example.proto",
}
